[tool.ruff]
# Enable flake8-bugbear (`B`) rules
select = ["E", "F", "B"]
# Exclude a variety of commonly ignored directories
exclude = [
    ".git",
    ".ruff_cache",
    "build",
    "dist",
]
ignore = [
    "E501",
    "B904",
]
# Allow lines to be as long as 140 characters
line-length = 140
